server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndyYHL/SpringBootManyDB.git
          search-paths: /**/config-pro
          username:
          password:
      #配置文件所在的分支
      label: master
#服务注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: 127.0.0.1
  client:
    #服务注册中心
    service-url: http://${eureka.instance.hostname}:8761/eureka/

