package com.qxst.e.meatballstartup.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class SsoUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.active_code
     *
     * @mbg.generated
     */
    private String active_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.usr_type_code
     *
     * @mbg.generated
     */
    private String usr_type_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.usr_type_name
     *
     * @mbg.generated
     */
    private String usr_type_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.tenant_id
     *
     * @mbg.generated
     */
    private Integer tenant_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.open_id
     *
     * @mbg.generated
     */
    private String open_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sso_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}